### ISSUE TITLE
Contex loss on classes that implements indirect interfaces

### ISSUE THREAD

**Issue by kalhauge** [petablox-project/petablox#22]
Running reachable methods analysis on the following program:

```java
public class Test {
  public static void main(String[] args) {
    I x = new C();
    x.test();
  }
}

interface I {
  public void test();
}

interface J extends I {}

class C implements J {
  public void test() {
    System.out.println("Test called");
  }
}
```

We would expect it to produce C.text as a reachable method but it doesn't. 

Petablox properties
```
petablox.datalog.engine=bddbddb
petablox.main.class=Test
petablox.run.analyses=reachable-methods
petablox.err.file=/dev/stderr
petablox.out.file=/dev/stdout
petablox.jvmargs=-Xmx4096m
petablox.runtime.jvmargs=-Xmx4096m
petablox.class.path=classes
petablox.reflect.kind=dynamic
petablox.run.ids=default
petablox.reflection.timeout=300000
petablox.dynamic.timeout=300000
petablox.reflection.haltonerr=false
petablox.args.default=
```

And reachable methods:
```
<Test: void main(java.lang.String[])>
<C: void <init>()>
<java.lang.Object: void <init>()>
<java.lang.Object: void <clinit>()>
<java.lang.Object: void registerNatives()>
```

**Comment by KihongHeo** [comment]
Hi. Thanks for the report.
I have fixed it and merged the commits into the main branch. Could you check it again?
Also I have fixed several performance and functionality bugs, so the analysis can become slightly different.

**Comment by KihongHeo** [comment]
Hi Christian. Can we close this issue? Did you check it on your side?

**Comment by kalhauge** [comment]
I didn't get around to test it yet. I'm out traveling, but I will try to run it as soon as I have time. Is it merged into master?

**Comment by KihongHeo** [comment]
Thanks! Yes. It is merged into master.

**Comment by kalhauge** [comment]
On the newest version of master 59180a9f898cb40086126caf8a5d1db252c689a8, I get:
```
Buildfile: /tmp/nix-build-petablox.drv-0/petablox-59180a9/build.xml

compile:

compile-j-part:
    [mkdir] Created dir: /tmp/nix-build-petablox.drv-0/petablox-59180a9/classes
    [javac] Compiling 467 source files to /tmp/nix-build-petablox.drv-0/petablox-59180a9/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.6
    [javac] /tmp/nix-build-petablox.drv-0/petablox-59180a9/src/petablox/analyses/invk/DomI.java:31: error: DomI is not abstract and does not override abstract method visit(JInvokeStmt) in IInvokeInstVisitor
    [javac] public class DomI extends ProgramDom<Unit> implements IInvokeInstVisitor {
    [javac]        ^
    [javac] /tmp/nix-build-petablox.drv-0/petablox-59180a9/src/petablox/analyses/inst/RelMgetClassInvkInst.java:24: error: RelMgetClassInvkInst is not abstract and does not override abstract method visit(JInvokeStmt) in IInvokeInstVisitor
    [javac] public class RelMgetClassInvkInst extends ProgramRel
    [javac]        ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 2 errors
    [javac] 1 warning
```

**Comment by KihongHeo** [comment]
Oh, sorry. I have fixed it. Please try it again.

**Comment by kalhauge** [comment]
Using the newest version of petablox 9fd8280b7e5503234cc303a19e2b0d5f8c282531, it still does not work. It only produces the following methods:

```
<Test: void main(java.lang.String[])>
<C: void <init>()>
<java.lang.Object: void <init>()>
<java.lang.Object: void <clinit>()>
<java.lang.Object: void registerNatives()>
```

**Comment by KihongHeo** [comment]
Oh I see. I fixed one more bug.
Now I get
```
<test.Test: void main(java.lang.String[])>
<java.lang.Object: void <init>()>
<java.lang.Object: void <clinit>()>
<java.lang.Object: void registerNatives()>
<java.lang.System: void <clinit>()>
<java.lang.System: void registerNatives()>
<test.C: void <init>()>
<test.C: void test()>
```
Please check it again.

**Comment by kalhauge** [comment]
Now it works, I think we can consider this issue closed.
